import Head from "next/head";
import Script from "next/script";
import Link from "next/link";

let menuNavbar = [
  { url: "/", menuTitle: "Home" },
  { url: "/dashboard", menuTitle: "Member Dashboard" },
];

// const menuNavbarDropdown = [{ url: "/", menuTitle: "Home" }];

export default function Navbar() {
  return (
    <div>
      <Head>
        <title>Template Rama Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <Script src="/js/jquery-3.3.1.slim.min.js"></Script>
        <Script src="/js/popper.min.js"></Script>
        <Script src="/js/bootstrap.min.js" strategy="afterInteractive"></Script>
      </Head>
      <nav className="navbar navbar-expand-lg navbar-dark bg-dark">
        <div className="container">
          <a className="navbar-brand" href="/">
            RadiusMan
          </a>

          <button
            className="navbar-toggler"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#navbarCollapse"
            aria-controls="navbarCollapse"
            aria-expanded="false"
            aria-label="Toggle navigation"
          >
            <span className="navbar-toggler-icon"></span>
          </button>

          <div className="collapse navbar-collapse" id="navbarCollapse">
            <ul className="navbar-nav">
              {menuNavbar.map((menu) => {
                return (
                  <li key={menu.url} className="nav-item">
                    <Link href={menu.url}>
                      <a className="nav-link">{menu.menuTitle}</a>
                    </Link>
                  </li>
                );
              })}
            </ul>
          </div>
        </div>
      </nav>
      <div className="m-4"></div>
      <Script src="/js/jquery-3.3.1.slim.min.js"></Script>
      <Script src="/js/popper.min.js"></Script>
      <Script src="/js/bootstrap.min.js" strategy="afterInteractive"></Script>
    </div>
  );
}
