import Head from "next/head";
import Image from "next/image";
import Script from "next/script";
import Link from "next/link";

const menuNavbar = [
  { url: "/", menuTitle: "Home" },
  { url: "/dashboard", menuTitle: "Dashboard" },
  { url: "/user/logout", menuTitle: "Logout" },
];

const menuNavbarDropdown = [
  {
    url: "/example/dashboard-prod",
    menuTitle: "Dashboard Table",
  },
  { url: "/example/zustand", menuTitle: "Zustand State Management" },
  { url: "/example/example", menuTitle: "Table & Modal" },
  { url: "/example/csr-swr", menuTitle: "CSR SWR" },
  {
    url: "/example/ssr-getserversideprops",
    menuTitle: "SSR - Server Side Props",
  },
  {
    url: "/example/table-useeffect-useswr",
    menuTitle: "useEffect useSwr Table",
  },
];

export default function NavbarMember() {
  return (
    <div>
      {/* Head */}
      <Head>
        <title>Template Rama Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Navbar */}
      <nav className="navbar navbar-expand-lg navbar-dark bg-dark">
        <div className="container">
          <a className="navbar-brand" href="#">
            RadiusMan
          </a>

          <button
            className="navbar-toggler"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#navbarCollapse"
            aria-controls="navbarCollapse"
            aria-expanded="false"
            aria-label="Toggle navigation"
          >
            <span className="navbar-toggler-icon"></span>
          </button>

          <div className="collapse navbar-collapse" id="navbarCollapse">
            <ul className="navbar-nav">
              {menuNavbar.map((menu) => {
                return (
                  <li key={menu.url} className="nav-item">
                    <Link href={menu.url} key={menu.url}>
                      <a className="nav-link">{menu.menuTitle}</a>
                    </Link>
                  </li>
                );
              })}
              <li className="nav-item dropdown">
                <a
                  className="nav-link dropdown-toggle"
                  id="navbar=dropdown-example"
                  data-bs-togle="dropdown"
                  href="#"
                  role="button"
                  data-bs-toggle="dropdown"
                  aria-expanded="false"
                >
                  Examples
                </a>
                <ul
                  className="dropdown-menu"
                  aria-labelledby="navbar=dropdown-example"
                >
                  {menuNavbarDropdown.map((menu) => {
                    return (
                      <li key={menu.url}>
                        <Link href={menu.url} key={menu.url}>
                          <a className="dropdown-item">{menu.menuTitle}</a>
                        </Link>
                      </li>
                    );
                  })}
                </ul>
              </li>
            </ul>
          </div>
        </div>
      </nav>
      {/* Spacer */}
      <div className="m-4"></div>
      {/* Script Tag */}
      <Script src="/js/jquery-3.3.1.slim.min.js"></Script>
      <Script src="/js/popper.min.js"></Script>
      <Script src="/js/bootstrap.min.js" strategy="afterInteractive"></Script>
    </div>
  );
}
